/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_linklistjni_JniUtil */

#ifndef _Included_com_example_linklistjni_JniUtil
#define _Included_com_example_linklistjni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_linklistjni_JniUtil
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_linklistjni_JniUtil_test
  (JNIEnv *, jobject);

/*
 * Class:     com_example_linklistjni_JniUtil
 * Method:    create
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_linklistjni_JniUtil_create
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_linklistjni_JniUtil
 * Method:    destory
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_linklistjni_JniUtil_destory
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_linklistjni_JniUtil
 * Method:    insert
 * Signature: (Lcom/example/linklistjni/Teacher;)V
 */
JNIEXPORT void JNICALL Java_com_example_linklistjni_JniUtil_insert
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_linklistjni_JniUtil
 * Method:    insertToSeq
 * Signature: (Lcom/example/linklistjni/Teacher;)V
 */
JNIEXPORT void JNICALL Java_com_example_linklistjni_JniUtil_insertToSeq
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_example_linklistjni_JniUtil
 * Method:    testSo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_linklistjni_JniUtil_testSo
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
