/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_socket_pool_JniUtil */

#ifndef _Included_com_example_socket_pool_JniUtil
#define _Included_com_example_socket_pool_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_socket_pool_JniUtil
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_socket_1pool_JniUtil_start
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
